In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('winemag-data-130k-v2.csv')

In [4]:
df

        Unnamed: 0  ...                                    winery
0                0  ...                                   Nicosia
1                1  ...                       Quinta dos Avidagos
2                2  ...                                 Rainstorm
3                3  ...                                St. Julian
4                4  ...                              Sweet Cheeks
...            ...  ...                                       ...
129966      129966  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967      129967  ...                                  Citation
129968      129968  ...                           Domaine Gresser
129969      129969  ...                      Domaine Marcel Deiss
129970      129970  ...                          Domaine Schoffit

[129971 rows x 14 columns]

Test with column unique number

In [56]:
df.nunique()

Unnamed: 0               129971
country                      43
description              119955
designation               37979
points                       21
price                       390
province                    425
region_1                   1229
region_2                     17
taster_name                  19
taster_twitter_handle        15
title                    118840
variety                     707
winery                    16757
dtype: int64

In [37]:
col_out =['description','designation','region_1','region_2','taster_twitter_handle','winery','title']

In [40]:
df_clean1 = df.drop(columns=col_out,axis=1).iloc[:,1:]

In [41]:
df_clean2 = df_clean1.dropna()

In [42]:
df_clean2

         country  points  ...         taster_name             variety
1       Portugal      87  ...          Roger Voss      Portuguese Red
2             US      87  ...        Paul Gregutt          Pinot Gris
3             US      87  ...  Alexander Peartree            Riesling
4             US      87  ...        Paul Gregutt          Pinot Noir
5          Spain      87  ...   Michael Schachner  Tempranillo-Merlot
...          ...     ...  ...                 ...                 ...
129966   Germany      90  ...  Anna Lee C. Iijima            Riesling
129967        US      90  ...        Paul Gregutt          Pinot Noir
129968    France      90  ...          Roger Voss      Gewürztraminer
129969    France      90  ...          Roger Voss          Pinot Gris
129970    France      90  ...          Roger Voss      Gewürztraminer

[96420 rows x 6 columns]

In [52]:
train, validate, test = np.split(df_clean2.sample(frac=1, random_state=42), 
                       [int(.5*len(df_clean2)), int(.75*len(df_clean2))])

In [53]:
train

          country  points  price         province     taster_name       variety
109284     Israel      91   55.0  Jerusalem Hills   Mike DeSimone  Petit Verdot
107439         US      88   50.0       California  Virginie Boone    Pinot Noir
31171          US      90   27.0       California   Matt Kettmann    Chardonnay
108103         US      86   29.0       California  Virginie Boone    Chardonnay
124719     France      90   24.0         Burgundy      Roger Voss    Chardonnay
...           ...     ...    ...              ...             ...           ...
1079           US      94   85.0           Oregon    Paul Gregutt    Chardonnay
93652          US      90   40.0       California  Virginie Boone    Chardonnay
39971   Australia      84   10.0  Australia Other  Joe Czerwinski          Rosé
16203       Italy      90   28.0   Southern Italy   Kerin O’Keefe         Fiano
35832          US      88   26.0       California  Virginie Boone        Merlot

[48210 rows x 6 columns]

In [54]:
validate

          country  points  ...        taster_name             variety
99085          US      90  ...       Paul Gregutt           Zinfandel
119153         US      87  ...   Sean P. Sullivan  Cabernet Sauvignon
61729          US      93  ...         Jim Gordon     Sparkling Blend
12368      France      85  ...         Roger Voss                Rosé
73646       Italy      89  ...      Kerin O’Keefe          Pinot Nero
...           ...     ...  ...                ...                 ...
125474    Austria      93  ...   Anne Krebiehl MW            Riesling
71435   Argentina      89  ...  Michael Schachner          Chardonnay
62159       Spain      90  ...  Michael Schachner         White Blend
112298         US      87  ...       Paul Gregutt          Pinot Noir
27067          US      94  ...      Matt Kettmann               Syrah

[24105 rows x 6 columns]

In [55]:
test

          country  points  ...         taster_name                   variety
50386   Argentina      86  ...   Michael Schachner                    Malbec
9677      Germany      90  ...  Anna Lee C. Iijima                  Riesling
124738    Germany      84  ...  Anna Lee C. Iijima                  Riesling
28719       Spain      86  ...   Michael Schachner                      Rosé
51850       Italy      93  ...       Kerin O’Keefe                Carricante
...           ...     ...  ...                 ...                       ...
8469        Chile      88  ...   Michael Schachner                    Malbec
74363      France      84  ...      Joe Czerwinski     Rhône-style Red Blend
103696    Germany      90  ...  Anna Lee C. Iijima                  Riesling
1126       France      84  ...          Roger Voss  Bordeaux-style Red Blend
21343    Portugal      86  ...          Roger Voss          Portuguese White

[24105 rows x 6 columns]